// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAViQrjwotXnlOgwZ9WMbMKD07jzq50HXI',
    appId: '1:870623304964:web:30861c6dbdf9ca83f5c451',
    messagingSenderId: '870623304964',
    projectId: 'trip-aa08a',
    authDomain: 'trip-aa08a.firebaseapp.com',
    storageBucket: 'trip-aa08a.appspot.com',
    measurementId: 'G-05ZX3PZH0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNJL9HZW5IbO_iHIiHJNb2eZg8lsmHANQ',
    appId: '1:870623304964:android:9420c2d557671758f5c451',
    messagingSenderId: '870623304964',
    projectId: 'trip-aa08a',
    storageBucket: 'trip-aa08a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz0weYX2DGs8IJNlNgx0uivhz7eMG0MKc',
    appId: '1:870623304964:ios:7f20d7953c43c62df5c451',
    messagingSenderId: '870623304964',
    projectId: 'trip-aa08a',
    storageBucket: 'trip-aa08a.appspot.com',
    iosBundleId: 'com.example.journease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz0weYX2DGs8IJNlNgx0uivhz7eMG0MKc',
    appId: '1:870623304964:ios:7f20d7953c43c62df5c451',
    messagingSenderId: '870623304964',
    projectId: 'trip-aa08a',
    storageBucket: 'trip-aa08a.appspot.com',
    iosBundleId: 'com.example.journease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAViQrjwotXnlOgwZ9WMbMKD07jzq50HXI',
    appId: '1:870623304964:web:29921aac9f0b8357f5c451',
    messagingSenderId: '870623304964',
    projectId: 'trip-aa08a',
    authDomain: 'trip-aa08a.firebaseapp.com',
    storageBucket: 'trip-aa08a.appspot.com',
    measurementId: 'G-QNYVN4CK46',
  );

}